# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 638)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(390, 260, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(600, 130, 171, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(620, 260, 151, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 190, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 190, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.photo = QtWidgets.QLabel(Form)
        self.photo.setGeometry(QtCore.QRect(20, 30, 361, 381))
        self.photo.setStyleSheet("")
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("3.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.comboBox_angle = QtWidgets.QComboBox(Form)
        self.comboBox_angle.setGeometry(QtCore.QRect(600, 90, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.comboBox_angle.setFont(font)
        self.comboBox_angle.setObjectName("comboBox_angle")
        self.comboBox_angle.addItem("")
        self.comboBox_angle.addItem("")
        self.comboBox_angle.addItem("")
        self.comboBox_angle.addItem("")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(390, 90, 211, 68))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "The Length you need:"))
        self.pushButton.setText(_translate("Form", "Calculate"))
        self.pushButton_2.setText(_translate("Form", "Reset"))
        self.comboBox_angle.setItemText(0, _translate("Form", "15°"))
        self.comboBox_angle.setItemText(1, _translate("Form", "22.5°"))
        self.comboBox_angle.setItemText(2, _translate("Form", "30°"))
        self.comboBox_angle.setItemText(3, _translate("Form", "45°"))
        self.label.setText(_translate("Form", "Please enter angle :"))
        self.label_2.setText(_translate("Form", "Please enter length :"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
