# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 651)
        self.photo = QtWidgets.QLabel(Form)
        self.photo.setGeometry(QtCore.QRect(150, 210, 231, 211))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("3.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(430, 190, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(430, 250, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.input_angle = QtWidgets.QLineEdit(Form)
        self.input_angle.setGeometry(QtCore.QRect(690, 210, 161, 31))
        self.input_angle.setObjectName("input_angle")
        self.input_angle.setFont(font)

        self.input_length = QtWidgets.QLineEdit(Form)
        self.input_length.setGeometry(QtCore.QRect(730, 270, 121, 31))
        self.input_length.setObjectName("input_length")
        self.input_length.setFont(font)

        self.btn_cal = QtWidgets.QPushButton(Form)
        self.btn_cal.setGeometry(QtCore.QRect(430, 330, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_cal.setFont(font)
        self.btn_cal.setObjectName("btn_cal")

        self.btn_reset = QtWidgets.QPushButton(Form)
        self.btn_reset.setGeometry(QtCore.QRect(600, 330, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_reset.setFont(font)
        self.btn_reset.setObjectName("btn_reset")

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(430, 390, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(750, 410, 101, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setFont(font)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Please enter angle A:"))
        self.label_2.setText(_translate("Form", "Please enter Length AB:"))
        self.btn_cal.setText(_translate("Form", "Calculate"))
        self.btn_reset.setText(_translate("Form", "Reset"))
        self.label_3.setText(_translate("Form", "The Length BC you need:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
